baseurl = "/"
languageCode = "en-US"
canonifyurls = true

# NOTE: https://gohugo.io/templates/pagination/#configuration
[pagination]
disableAliases = false
pagerSize = 6
path = 'page'

[params]
title = "Algorithms and Data Structures"
subtitle = "Musings on Computer Science"
copyright = "© 2018"

cover = "img/unibib.jpg"
description = "Musings on Computer Science Topics by the Team of the Chair of Algorithms and Data Structures under Prof. Dr. Hannah Bast"
metaDescription = ""
customCSS = []
RSSLink = ""

githubName = "ad-freiburg"

#logo = "img/logo.png"
orgName = "University of Freiburg"
orgWebsite = "https://ad.cs.uni-freiburg.de"
orgDescription = ""

showSupport = false

pageNotFoundTitle = "404 - Page not found"

[params.search]
enable = true
include_list_pages = false

[services]
[services.disqus]
shortname = ""
[services.googleAnalytics]
id = ''

[[menu.main]]
name = "Home"
url = "/"
weight = 200

#[[menu.main]]
#  name = "Some Topic"
#  url = "/tags/thetag"
#  weight = 100

#[[menu.main]]
#  name = "News"
#  url = "/categories/news/"
#  weight = 99

[[menu.main]]
name = "Research"
url = "/categories/research/"
weight = 98

[markup.goldmark.renderer]
unsafe = true

[module]
[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/search"

[[params.plugins.js]]
link = "js/search.js"

############################# Outputs ##############################
[outputs]
home = ["HTML", "SearchIndex"]

############################ Output Format ###########################
[outputFormats]
[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true
